name: publish

on:
  push:
    tags:
      - '*-snapshot'

jobs:
  snapshot:
    env:
      IS_RELEASE: false
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      SIGNING_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
      SIGNING_KEY: ${{ secrets.GPG_FILE_BASE64 }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Set credentials
        run: |
          echo "signing.keyId=${SIGNING_KEY_ID}" > ~/.gradle/gradle.properties
          echo "signing.password=${SIGNING_PASSWORD}" >> ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=${HOME}/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
          echo ${SIGNING_KEY} | base64 -d > ~/.gradle/secring.gpg

      - name: Publish iris-mock
        run: ./gradlew :iris-mock:publish

      - name: Publish iris-mock-plugin
        run: ./gradlew :iris-mock-plugin:publish

      - name: Publish iris-mock-compiler
        run: ./gradlew :iris-mock-compiler:publish
